# serverless.yml
service: aws-app-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  memorySize: 512

functions:
  imageFunc:
    handler: image.handler
    events:
      - http:
          path: image
          method: get
      - http:
          path: image/{id}
          method: get
      - http:
          path: image
          method: post
      - http:
          path: image/{id}
          method: put
      - http:
          path: image/{id}
          method: delete

plugins:
  - serverless-offline
